In [3]:
import pandas as pd
import numpy as np
import random

# Set random seed for reproducibility
np.random.seed(42)

# Simulated categories
channels = ['Facebook', 'Instagram', 'Google Ads', 'TikTok', 'Email']
age_groups = ['18-24', '25-34', '35-44', '45-54', '55+']
genders = ['Male', 'Female', 'All']
campaign_names = [f"FashionPromo_{i}" for i in range(1, 21)]

# Function to simulate a single row of campaign data
def generate_campaign_row():
    campaign = random.choice(campaign_names)
    channel = random.choice(channels)
    age = random.choice(age_groups)
    gender = random.choice(genders)
    
    budget = round(np.random.uniform(500, 5000), 2)
    impressions = int(budget * np.random.uniform(10, 30))
    ctr = round(np.random.uniform(0.01, 0.12), 4)
    clicks = int(impressions * ctr)
    conversion_rate = round(np.random.uniform(0.005, 0.10), 4)
    conversions = int(clicks * conversion_rate)
    revenue = round(conversions * np.random.uniform(30, 150), 2)

    return {
        "Campaign Name": campaign,
        "Channel": channel,
        "Target Age Group": age,
        "Target Gender": gender,
        "Budget ($)": budget,
        "Impressions": impressions,
        "Clicks": clicks,
        "CTR (%)": round(ctr * 100, 2),
        "Conversions": conversions,
        "Conversion Rate (%)": round(conversion_rate * 100, 2),
        "Revenue ($)": revenue
    }

# Generate 1000 rows
data = [generate_campaign_row() for _ in range(1000)]
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("marketing_campaign_data.csv", index=False)
print("✅ Dataset generated and saved as 'marketing_campaign_data.csv'")

✅ Dataset generated and saved as 'marketing_campaign_data.csv'

In [2]:
df

,Campaign Name,Channel,Target Age Group,Target Gender,Budget ($),Impressions,Clicks,CTR (%),Conversions,Conversion Rate (%),Revenue ($)
0,FashionPromo_20,Google Ads,55+,Male,2185.43,63408,5738,9.05,355,6.19,17296.39
1,FashionPromo_12,Instagram,45-54,Male,1201.98,13416,1412,10.53,87,6.21,10002.28
2,FashionPromo_10,Instagram,18-24,Male,592.63,17422,1770,10.16,44,2.52,2280.04
3,FashionPromo_14,Facebook,18-24,All,1325.32,21317,1443,6.77,66,4.60,4286.53
4,FashionPromo_16,TikTok,35-44,All,3253.34,41609,1751,4.21,69,3.98,5846.26
...,...,...,...,...,...,...,...,...,...,...,...
995,FashionPromo_8,Facebook,18-24,Male,2510.27,31300,1023,3.27,5,0.51,173.56
996,FashionPromo_17,Email,55+,All,4897.78,72717,6035,8.30,511,8.47,49096.50
997,FashionPromo_14,Google Ads,35-44,Male,1189.15,29208,2219,7.60,165,7.45,20190.98
998,FashionPromo_19,Email,18-24,Male,4889.35,104980,4997,4.76,332,6.66,12686.68
999,FashionPromo_4,Instagram,18-24,All,4538.29,56218,2591,4.61,213,8.25,21657.30